#!/usr/bin/php
<?php
echo "VKSCHOOLBOT v1.3 SETUP\n";
echo "Эта версия в разработке. Использование её может быть небезопасно!\n\n\n";
fclose(fopen("bot.db", 'w')); //Just create file
chmod("bot.db", 0666);
$db = new SQLite3("bot.db");
echo "База данных создана\n";
$create_tables_query = "CREATE TABLE Homeworkdata "
        . "(ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "
        . "Subject VARCHAR(50) NOT NULL UNIQUE, Homework TEXT DEFAULT \"\");"
        . "CREATE TABLE UserData (user VARCHAR(50) NOT NULL PRIMARY KEY, "
        . "pass CHAR(64) NOT NULL);"
        . "create table PassKeys (passkey char(64) not null, "
        . "user varchar(50) not null, ip varchar(45) not null, "
        . "expiration_time integer not null, "
        . "FOREIGN KEY (user) REFERENCES UserData(user) "
        . "on delete cascade on update cascade);";
if($db->exec($create_tables_query))
{
    echo "Таблицы созданы\n";
}
echo "Введите имя пользователя API: ";
$user = trim(fgets(STDIN));
echo "Введите пароль пользователя API: ";
$pass = hash('sha256', trim(fgets(STDIN)));
$insert_user_query = "INSERT INTO UserData (user, pass) VALUES (\"$user\",\"$pass\")";
$db->exec($insert_user_query);
$db->close();
echo "Setup complete!";