name: CI

on: 
  push: 
  pull_request:
    branches: [master, development]
jobs:
  build-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: composer install --no-progress --no-suggest
    - run: vendor/bin/phpunit -c phpunit/phpunit.xml