 
name: Tests

on:
  push:
    branches: [ master, development]
  pull_request:
    branches: [ master, development]

jobs:
  Testing:
    runs-on: ubuntu-latest
    container: kriseev/ubuntu_apache_curl
    steps:
    - name: Checkout project 
      uses: actions/checkout@v2
      with:
        repository: KriseevM/vkschoolbot
    - name: Install dependencies
      run: composer install
    - name: Copy files to www dir
      run: cp -r $(pwd) /var/www/html/vkschoolbot
    - name: Chown all files to www-data
      run: chown -R www-data /var/www/html/vkschoolbot
    - name: Start Apache Server
      run: service apache2 start
    - name: Run tests
      run: for file in tests/*; do echo "Running $file"; php "$file"; done;